site_name: EMR Best Practices Guides
repo_name: "aws/aws-emr-best-practices"
repo_url: "https://github.com/aws/aws-emr-best-practices"
docs_dir: "content"
theme: 
  name: material
  features: 
    - tabs
nav:
  - Introduction: 'index.md'
  - 1 - Cost Optimizations:
    - Introduction: 'cost_optimization/introduction.md'
    - Best Practices: 'cost_optimization/best_practices.md'
  - 2 - Reliability:
    - Introduction: 'reliability/introduction.md'
    - Best Practices: 'reliability/best_practices.md'   
  - 3 - Security: 
    - Introduction: 'security/introduction.md'
    - Best Practices: 'security/best_practices.md'    
  - 4 - Features: 
    - 4.1 - Managed Scaling: 'features/managed_scaling/best_practices.md'     
    - 4.2 - Spot Usage: 'features/spot_usage/best_practices.md'              
  # - 4 - Performance Efficiency: 'index.md'
  # - 5 - Operational Excellence: 'index.md'
  - 5 - Applications:
      - 5.1 Spark:
        - Introduction: 'applications/spark/introduction.md'
        - Best Practices: 'applications/spark/best_practices.md'
    # - Hive: 'index.md'      
    # - Introduction: 'index.md'
  # - Performance:
  #   - Introduction: 'index.md'
  # - Reliability:
  #   - Introduction: 'index.md'
  # - Applications:
  #   - Spark: 'index.md' 
  #   - Hive: 'index.md'
  #   - Hbase: 'index.md'
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite
    - attr_list
    - md_in_html
